Batch update frequency error
I was trying to execute the training with update frequency set to
"batch" instead of epoch, when i got this error:

> File
"/opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p0.11/lib/spark/python/pyspark/worker.py",
line 111, in main
>     process()
>   File
"/opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p0.11/lib/spark/python/pyspark/worker.py",
line 106, in process
>     serializer.dump_stream(func(split_index, iterator), outfile)
>   File
"/opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p0.11/lib/spark/python/pyspark/serializers.py",
line 263, in dump_stream
>     vs = list(itertools.islice(iterator, batch))
>   File
"/home/data_scientists_reply/deep_learning_sandbox/anaconda2/lib/python2.7/site-packages/elephas/spark_model.py",
line 311, in train
>     X = slice_X(x_train, batch_ids)
>   File
"/home/data_scientists_reply/deep_learning_sandbox/anaconda2/lib/python2.7/site-packages/Keras-1.2.2-py2.7.egg/keras/engine/training.py",
line 306, in slice_X
>     return X[start]
> IndexError: index 132 is out of bounds for axis 0 with size 132
>
>         at
org.apache.spark.api.python.PythonRDD$$anon$1.read(PythonRDD.scala:138)
>         at
org.apache.spark.api.python.PythonRDD$$anon$1.<init>(PythonRDD.scala:179)
>         at
org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:97)
>         at
org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297)
>         at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
>         at
org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
>         at org.apache.spark.scheduler.Task.run(Task.scala:88)
>         at
org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
>         at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>         at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
>         at java.lang.Thread.run(Thread.java:745)
>

I think it may be caused by the variable i edited in the
pull(nb_train_sample)